name: Build, Test & Push MongoDB Image

on:
  :
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/mongo-custom

jobs:
  build-and-push:
    runs-on: self-hosted  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push MongoDB Image
        run: |
          docker build -f Dockerfile.mangoDB -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Run MongoDB Smoke Test
        env:
          MONGO_ROOT_PASSWORD: ${{ secrets.SERVER_PASS }}
        run: |
          docker run -d --name mongo-test \
            -e MONGO_INITDB_ROOT_USERNAME=root \
            -e MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD \
            -p 27017:27017 $IMAGE_NAME:latest

          echo "Waiting for MongoDB to start..."
          for i in {1..15}; do
            if docker exec mongo-test mongosh --eval 'db.runCommand({ping:1})' admin -u root -p $MONGO_ROOT_PASSWORD; then
              echo "MongoDB is ready!"
              break
            fi
            sleep 5
          done

      - name: Cleanup Smoke Test
        if: always()
        run: |
          docker stop mongo-test || true
          docker rm mongo-test || true
