name: Deploy file from another repo via SSH key

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Target server IP"
        required: true
      server_user:
        description: "Target server username"
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo A (current repo)
        uses: actions/checkout@v3

      - name: Checkout Repo B (private via GitHub deploy key)
        uses: actions/checkout@v3
        with:
          repository: ROHIT6350/test_private 
          ssh-key: ${{ secrets.PAT_TOKEN }} 
          ref: main
          path: repo-b
          persist-credentials: false
          ssh-strict: false

      - name: Debug (list files from Repo B)
        run: ls -la repo-b/

      - name: Test SSH connection to server
        run: |
          echo "${{ secrets.SERVER_IP }}" > server_key
          chmod 600 server_key
          ssh -o StrictHostKeyChecking=no -i server_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH connection successful'"

      - name: Copy file from Repo B to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "repo-b/index.php"
          target: "/data"
          overwrite: true
          debug: true

      - name: Verify deployment
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > server_key
          chmod 600 server_key
          ssh -o StrictHostKeyChecking=no -i server_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "ls -la /data/index.php && echo 'File successfully deployed'"
