name: Test NTP Server

on: [push]

jobs:
  ntp-server-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install chrony (NTP server)
      run: |
        sudo apt update
        sudo apt install -y chrony

    - name: Configure chrony as a local NTP server
      run: |
        sudo bash -c 'cat > /etc/chrony/chrony.conf' <<EOF
        allow 127.0.0.1
        bindaddress 127.0.0.1
        local stratum 10
        manual
        logdir /var/log/chrony
        EOF

    - name: Start chrony service
      run: |
        sudo chronyd -d &
        sleep 5  # Give it time to s
