name: new code kroger

on:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: wel-come 
        run: echo "hello rohit"

      - name: adding new file
        run: |
          touch file1
          echo " hello kroger team" > file1
          date

      - name: ipmapping
        run: echo "hostname"

      - name: checking the hostname
        run: |
          hostnamectl
          cat /etc/resolv.conf
          ip a  
          timedatectl
