name: Install XAMPP on Main Server

on: [push]

jobs:
  install-xampp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key

    - name: Install XAMPP on server via SSH
      run: |
        ssh -i ssh_key \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        # Check if XAMPP already installed
        if [ -d "/opt/lampp" ]; then
          echo " XAMPP already installed"
          sudo /opt/lampp/lampp status
          exit 0
        fi

        echo "[INFO] Installing dependencies"
        sudo apt update
        sudo apt install -y wget

        echo "[INFO] Downloading XAMPP installer"
        wget https://www.apachefriends.org/xampp-files/8.2.12/xampp-linux-x64-8.2.12-0-installer.run -O /tmp/xampp-installer.run
        
        if [ ! -f "/tmp/xampp-installer.run" ]; then
          echo " Failed to download XAMPP"
          exit 1
        fi

        echo "[INFO] Making installer executable"
        chmod +x /tmp/xampp-installer.run
        
        echo "[INFO] Installing XAMPP silently"
        sudo /tmp/xampp-installer.run --mode unattended
        
        echo "[INFO] Starting XAMPP service"
        sudo /opt/lampp/lampp start
        
        echo "[INFO] Checking XAMPP status"
        sudo /opt/lampp/lampp status

        echo "[INFO] Setting permissions"
        sudo chown -R $USER:$USER /opt/lampp/htdocs/

        echo "XAMPP installed successfully on ${{ secrets.SERVER_IP }}"
        echo " Access: http://${{ secrets.SERVER_IP }}/"
        EOF

    - name: Cleanup SSH key
      run: rm -f ssh_key

    - name: Verify installation
      run: |
        echo "XAMPP installation completed on server: ${{ secrets.SERVER_IP }}"
