name: new code kroger

on: [push]

jobs:
  build:  # You must name the job (e.g., "build")
    runs-on: ubuntu-latest

    steps:
      - name: wel-come  # Add a space after "-"
        run: echo "hello rohit"
