name: Test NTP Server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP address'
        required: true
        default: '192.168.0.132'
      server_user:
        description: 'Server username'
        required: true
        default: 'root'

jobs:
  ntp-server-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install and configure NTP on remote server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ github.event.inputs.server_ip }}
        username: ${{ github.event.inputs.server_user }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          echo "[INFO] Updating package list"
          sudo apt-get update
          
          echo "[INFO] Installing chrony (NTP server)"
          sudo apt-get install -y chrony
          
          echo "[INFO] Configuring chrony as NTP server"
          sudo bash -c 'cat > /etc/chrony/chrony.conf' <<EOF
          allow ${{ github.event.inputs.server_ip }}/24
          bindaddress ${{ github.event.inputs.server_ip }}
          local stratum 10
          logdir /var/log/chrony
          EOF
          
          echo "[INFO] Restarting chrony service"
          sudo systemctl restart chrony
          sudo systemctl enable chrony
          
          echo "[INFO] Allowing NTP through firewall"
          sudo ufw allow 123/udp
          
          echo "[INFO] Checking chrony status"
          sudo systemctl status chrony --no-pager
          
          echo "[INFO] Verifying NTP synchronization"
          sleep 3
          chronyc sources
          chronyc tracking
          
          echo " NTP server configured on ${{ github.event.inputs.server_ip }}"
