name: Install NTP Server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP address'
        required: true
        default: '192.168.0.132'
      server_user:
        description: 'Server username'
        required: true
        default: 'root'

jobs:
  install-xampp:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install XAMPP on main server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update
            wget https://www.apachefriends.org/xampp-files/8.2.0/xampp-linux-x64-8.2.0-0-installer.run -O /tmp/xampp-installer.run
            chmod +x /tmp/xampp-installer.run
            sudo /tmp/xampp-installer.run --mode unattended
            sudo /opt/lampp/lampp start
            sudo /opt/lampp/lampp status
