name: Install XAMPP on Server

on: [push]

jobs:
  install-xampp: 
    runs-on: slef-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install XAMPP on main server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "[INFO] Downloading XAMPP installer"
            wget https://www.apachefriends.org/xampp-files/8.2.0/xampp-linux-x64-8.2.0-0-installer.run -O /tmp/xampp-installer.run
            
            echo "[INFO] Making installer executable"
            chmod +x /tmp/xampp-installer.run
            
            echo "[INFO] Installing XAMPP silently"
            sudo /tmp/xampp-installer.run --mode unattended
            
            echo "[INFO] Starting XAMPP service"
            sudo /opt/lampp/lampp start
            
            echo "[INFO] Checking XAMPP status"
            sudo /opt/lampp/lampp status
