name: Install NTP Server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP address'
        required: true
        default: '192.168.0.132'
      server_user:
        description: 'Server username'
        required: true
        default: 'rohit'

jobs:
  install-ntp-server:
    runs-on: self-hosted

    steps:
      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Install NTP server
        run: |
          ssh -i ssh_key \
              -o StrictHostKeyChecking=no \
              ${{ github.event.inputs.server_user }}@${{ github.event.inputs.server_ip }} bash -c "
                sudo apt-get update &&
                sudo apt-get install -y ntp &&
                sudo systemctl start ntp &&
                sudo systemctl enable ntp &&
                sudo systemctl status ntp --no-pager
              "
