name: Install XAMPP Server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP address'
        required: true
        default: '192.168.0.132'
      server_user:
        description: 'Server username'
        required: true
        default: 'rohit'

jobs:
  install-xampp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key

    - name: Install XAMPP via SSH
      run: |
        ssh -i ssh_key \
            -o StrictHostKeyChecking=no \
            ${{ github.event.inputs.server_user }}@${{ github.event.inputs.server_ip }} << 'EOF'
          # Check if XAMPP already installed
          if [ -d "/opt/lampp" ]; then
            echo "XAMPP already installed"
            sudo /opt/lampp/lampp status
            exit 0
          fi

          echo "[INFO] Installing dependencies"
          sudo apt update
          sudo apt install -y wget

          echo "[INFO] Downloading XAMPP installer"
          wget https://www.apachefriends.org/xampp-files/8.2.12/xampp-linux-x64-8.2.12-0-installer.run -O /tmp/xampp-installer.run
          
          echo "[INFO] Making installer executable"
          chmod +x /tmp/xampp-installer.run
          
          echo "[INFO] Installing XAMPP silently"
          sudo /tmp/xampp-installer.run --mode unattended
          
          echo "[INFO] Starting XAMPP service"
          sudo /opt/lampp/lampp start
          
          echo "[INFO] Checking XAMPP status"
          sudo /opt/lampp/lampp status
          
          echo " XAMPP installed successfully on $(hostname)"
        EOF
