name: Install Samba Server

:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Target Server IP Address'
        required: true
        default: '192.168.0.132'
      server_user:
        description: 'Server SSH Username'
        required: true
        default: 'rohit'

jobs:
  install-samba:
    runs-on: self-hosted  # Important: Use a self-hosted runner in your network

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Samba Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ github.event.inputs.server_ip }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Install Samba
            sudo apt-get update
            sudo apt-get install -y samba

            # Create public share
            sudo mkdir -p /srv/samba/share
            sudo chmod -R 0777 /srv/samba/share

            # Create private share and user
            sudo useradd sambauser -m
            echo "sambauser:password" | sudo chpasswd
            sudo smbpasswd -a -n sambauser

            sudo mkdir -p /srv/samba/private
            sudo chown sambauser:sambauser /srv/samba/private
            sudo chmod 0700 /srv/samba/private

            # Configure smb.conf
            sudo bash -c 'cat >> /etc/samba/smb.conf <<EOL

[PublicShare]
   path = /srv/samba/share
   browsable = yes
   writable = yes
   guest ok = yes
   read only = no

[PrivateShare]
   path = /srv/samba/private
   browsable = yes
   writable = yes
   guest ok = no
EOL'

            # Restart Samba services
            sudo systemctl restart smbd nmbd
            sudo systemctl enable smbd nmbd

            # Open firewall
            sudo ufw allow Samba

            # Test Samba config
            testparm
