name: Terraform

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Target Server IP Address'
        required: true
        default: '192.168.0.132'
      server_user:
        description: 'Server SSH Username'
        required: true
        default: 'rohit'

jobs:
  terraform-docker:
    runs-on: slef-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      #  Docker Hub Login 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Docker Image 
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apache-server:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apache-server:latest

      #  Terraform Steps 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="docker_username=${{ secrets.DOCKER_USERNAME }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="docker_username=${{ secrets.DOCKER_USERNAME }}"
