name: CI for XAMPP Web Server

 :
  :
    branches: [ "main" ]
  workflow_dispatch:   # allow manual trigger

jobs:
  build:            # Collect website code from repositories.
    name: Build Stage - Checkout Repositories
    runs-on: self-hosted

    steps:
      - name: Checkout Repo A (public repo)
        uses: actions/checkout@v3

      - name: Checkout Repo B (test_private via GitHub deploy key)
        uses: actions/checkout@v3
        with:
          repository: ROHIT6350/test_private-
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
          ref: main
          path: web
          persist-credentials: false
          ssh-strict: false

      - name: Archive Website Code
        run: |
          tar -czf website.tar.gz -C web .

      - name: Upload Website Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-code
          path: website.tar.gz

  deploy:
    name: Deploy Stage - Transfer to XAMPP Server
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download Website Artifact
        uses: actions/download-artifact@v4
        with:
          name: website-code
          path: .

      - name: Extract Artifact
        run: |
          rm -rf web
          mkdir -p web
          tar -xzf website.tar.gz 
      

      - name: Upload Files to Staging Directory (no sudo needed)
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          rm -rf .git .github web/.git web/.github
          scp -i id_rsa -o StrictHostKeyChecking=no -r * \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/deploy/

      - name: Move Files into XAMPP htdocs (with sudo)
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "echo '${{ secrets.SERVER_PASS }}' | sudo -S mkdir -p /opt/lampp/htdocs && \
             echo '${{ secrets.SERVER_PASS }}' | sudo -S rm -rf /opt/lampp/htdocs/* && \
             echo '${{ secrets.SERVER_PASS }}' | sudo -S mv /home/${{ secrets.SERVER_USER }}/deploy/* /opt/lampp/htdocs/ && \
             echo '${{ secrets.SERVER_PASS }}' | sudo -S chown -R rohit:rohit /opt/lampp/htdocs && \
             echo '${{ secrets.SERVER_PASS }}' | sudo -S chmod -R 755 /opt/lampp/htdocs"

      - name: Restart Apache in XAMPP
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "echo '${{ secrets.SERVER_PASS }}' | sudo -S systemctl restart apache2"

  test:
    name: Test Stage - Validate Website
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Wait for Web Server
        run: sleep 10

      - name: Test Website on Remote Server
        run: |
          curl -IL http://${{ secrets.SERVER_IP }} | grep "200 OK" || exit 1
