name: Deploy file from another repo via SSH key

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Target server IP"
        required: true
      server_user:
        description: "Target server username"
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          repository: ROHIT6350/test_private 
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }} 
          ref: main
          path: private-repo
          persist-credentials: false

      - name: List files from private repo
        run: ls -la private-repo/

      - name: Test SSH connection to server
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > server_key
          chmod 600 server_key
          ssh -o StrictHostKeyChecking=no -i server_key ${{ github.event.inputs.server_user }}@${{ github.event.inputs.server_ip }} "echo 'SSH connection successful'"

      - name: Copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "private-repo/index.php"
          target: "/data"
          overwrite: true

      - name: Verify deployment
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > server_key
          chmod 600 server_key
          ssh -o StrictHostKeyChecking=no -i server_key ${{ github.event.inputs.server_user }}@${{ github.event.inputs.server_ip }} "ls -la /data/index.php && echo 'Deployment successful!'"

